// angular-cli/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  showAlert = false;
}

<main cds-layout="vertical gap:md p:lg">
  <h1 cds-text="heading">Clarity + Angular Starter</h1>

  <div cds-layout="horizontal gap:sm">
    <a cds-text="link" href="https://clarity.design/storybook/core">Clarity Docs</a>
    <a cds-text="link" href="https://angular.io">Angular Docs</a>
  </div>

  <cds-button action="outline" (click)="showAlert = true">Hello There</cds-button>

  <cds-alert-group status="info" *ngIf="showAlert">
    <cds-alert [closable]="true" (closeChange)="showAlert = false">
      you are a bold one...
    </cds-alert>
  </cds-alert-group>
</main>

// create-react-app/src/App.tsx
import React, { useState } from 'react';

import { CdsButton } from '@cds/react/button';
import { CdsAlert, CdsAlertGroup } from '@cds/react/alert';
import './App.css';

interface AppProps { }

export function App(props: AppProps) {
  const [show, setShow] = useState<boolean>(false);

  return (
    <main cds-layout="vertical gap:lg p:lg">
      <h1 cds-text="heading">Clarity + React Starter</h1>

      <div cds-layout="horizontal gap:sm">
        <a cds-text="link" href="https://clarity.design/storybook/core">Clarity Docs</a>
        <a cds-text="link" href="https://reactjs.org/">React Docs</a>
      </div>

      <CdsButton action="outline" onClick={() => setShow(true)}>Hello There</CdsButton>

      {show ? (
        <CdsAlertGroup status="info">
          <CdsAlert onCloseChange={() => setShow(false)} closable>you are a bold one...</CdsAlert>
        </CdsAlertGroup>
      ) : (
        ''
      )}
    </main>
  );
}
